"""
Generate machines.json from the simulator metadata.

This script reads the machines.csv file generated by the simulator and
creates the machines.json metadata file used by the synthetic document
generation pipeline.

The simulator is considered the source of truth for:
- Machine ID
- Machine name
- Installation date

The document generator enriches each machine with:
- Equipment family
- Equipment series
- Model number
- Sensor configuration
"""

import json
import pandas as pd

from document_generator.config import MACHINES_CSV, MACHINES_JSON


# ==============================================================================
# Equipment Families
# ==============================================================================

FAMILIES = [
    ("Industrial Electric Motors", "EM-500", range(1, 21)),
    ("Centrifugal Pumps", "CP-200", range(21, 41)),
    ("Rotary Air Compressors", "AC-300", range(41, 61)),
    ("Hydraulic Power Units", "HP-400", range(61, 81)),
    ("Industrial Ventilation Fans", "VF-150", range(81, 101)),
]


# ==============================================================================
# Helper Function
# ==============================================================================

def get_machine_information(machine_number: int) -> dict:
    """
    Determine the family, series and model corresponding to a machine number.

    Parameters
    ----------
    machine_number : int
        Machine numerical identifier (1-100)

    Returns
    -------
    dict
        Dictionary containing family, series and model.
    """

    for family, series, machine_range in FAMILIES:

        if machine_number in machine_range:

            model_number = machine_number - machine_range.start + 1

            return {
                "family": family,
                "series": series,
                "model": f"{series}-{model_number:02d}",
            }

    raise ValueError(f"Unknown machine number: {machine_number}")


# ==============================================================================
# Main
# ==============================================================================

def main():

    print("Loading simulator machine metadata...")

    df = pd.read_csv(MACHINES_CSV)

    machines = []

    for _, row in df.iterrows():

        machine_number = int(row["id"])

        machine_info = get_machine_information(machine_number)

        machine = {
            "id": machine_number,
            "machine_id": f"M{machine_number:03d}",
            "machine_name": row["machine_name"],
            "family": machine_info["family"],
            "series": machine_info["series"],
            "model": machine_info["model"],
            "installation_date": row["installation_date"],
            "sensor_configuration": [
                "Temperature",
                "Rotational Speed",
                "Vibration",
                "Pressure",
                "Current"
            ]
        }

        machines.append(machine)

    with open(MACHINES_JSON, "w", encoding="utf-8") as file:
        json.dump(machines, file, indent=4)

    print(f"Successfully generated {len(machines)} machines.")
    print(f"Output saved to:\n{MACHINES_JSON}")


# ==============================================================================
# Entry Point
# ==============================================================================

if __name__ == "__main__":
    main()